[web]
web01 ansible_host=192.168.56.21

[database]
db01 ansible_host=192.168.56.22

[nas]
nas01 ansible_host=192.168.56.23

[linux_servers:children]
web
database
nas

[linux_servers:vars]
ansible_users=vagrant
ansible_ssh_private_key_file=~/.ssh/id_rsa
