[web]
web01 ansible_host=192.168.56.21

[database]
db01 ansible_host=192.168.56.24

[nas]
nas01 ansible_host=192.168.56.23

[linux_servers:children]
web
database
nas

[linux_servers:vars]
ansible_user=admin
ansible_password=@Weownthings1990
